oe-alliance/bootmenu

sf8008/images

Add PKT Hyperion ULR for sf8008

---

sf8008/images
ustym4kpro/images

PKT Hyperion switched to new multiboot

---

zgemmah9combo/images
zgemmah9twin/images

add Add PKT Hyperion ULR for H9combo & H9twin

---

sf8008/images
sf8008m/images
ustym4kpro/images
zgemmah9combo/images
zgemmah9twin/images

Add Octagon sf8008m image. Please add

[PKTeam] add sf8008m image

---

h9combo/images
sf8008/images
sf8008m/images
ustym4kpro/images
zgemmah9combo/images
zgemmah9twin/images

[PKTeam] add Hyperion 8 image

---

sf8008/images

Update Image V10547 SF8008

---

sf8008m/images

Update Image V10547 SF8008m

---

sf8008/images

Update Image V10548

---

sf8008m/images

Update Image V10549

---

sf8008/images

Update Image V10550

---

sf8008m/images

Octagon Factory Image

---

sf8008/images

Factory Image Octagon SF8008

---

sf8008/images

Octagon Factory Image correcture date

Octagon Factory Image correcture date

---

sf8008/images

add. Image Version

---

sf8008/images

rename file name

---

sf8008/images

Update Image V10551

---

sf8008/images

Update Image V10555 SF8008

---

sf8008m/images

Update Image V10555 SF8008M

---

sf8008/images

Update Image SW V10557 SF8008

---

sf8008m/images

Update Image SW V10557 SF8008M

Update Image SW V10557 SF8008M

---

sf8008/images

Update Image SW V10558 OCTAGON SF8008

Update Image SW V10558 OCTAGON SF8008

---

sf8008m/images

Update Image SW V10558 OCTAGON SF8008M

Update Image SW V10558 OCTAGON SF8008M

---

sf8008/images

Update Image SW V10559 OCTAGON SF8008

Update Image SW V10559 OCTAGON SF8008

---

sf8008m/images

Update Image SW V10559 OCTAGON SF8008M

Update Image SW V10559 OCTAGON SF8008M

---

sf8008/images

Update Image SW V10561 OCTAGON SF8008

Update Image SW V10561 OCTAGON SF8008

---

sf8008m/images

Update Image SW V10561 OCTAGON SF8008M MINI

Update Image SW V10561 OCTAGON SF8008M MINI

---

sf8008m/images

Update Image SW V10562 OCTAGON SF8008M mini

Update Image SW V10562 OCTAGON SF8008M mini

---

sf8008/images

Update Image SW V10562 OCTAGON SF8008

Update Image SW V10562 OCTAGON SF8008

---

sf8008/images

Update Image SW V10563 OCTAGON SF8008

Update Image SW V10563 OCTAGON SF8008

---

sf8008m/images

Update Image SW V10563 OCTAGON SF8008M mini

Update Image SW V10563 OCTAGON SF8008M mini

---

sf8008m/images

Update Image SW V10566 OCTAGON SF8008 M Mini

Update Image SW V10566 OCTAGON SF8008 M Mini

---

sf8008/images

Update Image SW V10566 OCTAGON SF8008

Update Image SW V10566 OCTAGON SF8008

---

h8/images
zgemmah82h/images

todo (fix current image for h82h)

add h8 - zgemmah82h

---

sf8008/images

Update Image SW V10567 OCTAGON SF8008

Update Image SW V10567 OCTAGON SF8008

---

sf8008m/images

Update Image SW V10567 OCTAGON SF8008M MINI

Update Image SW V10567 OCTAGON SF8008M MINI

---

gbip4k/images
gbtrio4k/images
hd60/images
pulse4k/images
pulse4kmini/images
sf8008/images
viper4k/images

We're using our updated version of current.php which has more abilities: https://github.com/OpenVisionE2/web-tools

Add some Open Vision links

---

sf8008m/images

Update OCTAGON Define OS SW V10568 SF8008M

Update OCTAGON Define OS SW V10568 SF8008M

---

sf8008/images

Update OCTAGON Define OS SW V10568 SF8008

Update OCTAGON Define OS SW V10568 SF8008

---

sf8008/images

OCTAGON Define OS Update Image SW V10569 SF8008

OCTAGON Define OS Update Image SW V10569 SF8008

---

sf8008m/images

OCTAGON Define OS Update Image SW V10569 SF8008M

OCTAGON Define OS Update Image SW V10569 SF8008M

---

sf8008m/images

Update Software OCTAGON Define OS V10571 SF8008M

Update Software OCTAGON Define OS V10571 SF8008M

---

sf8008/images

Update Software OCTAGON Define OS V10571 SF8008

Update Software OCTAGON Define OS V10571 SF8008

---

sf8008/images

Verison Number correcture v10571

Verison Number correcture v10571

---

sx988/images

Update Image SW OCTAGON Define OS SX988 4K V10572

Update Image SW OCTAGON Define OS SX988 4K V10572

---

sx988/images

Firmware Upgrade OCTAGON SX988 4K DUAL OS V10573

Firmware Upgrade OCTAGON SX988 4K DUAL OS V10573

---

php/current.php

works on get _usb.zip and _mmc.zip 
Tested on H8.2H & some
USB.ZIP = http://image.egami-image.com/10.0/current.php?open=zgemmah82h
MMC.ZIP = http://image.egami-image.com/10.0/current.php?open=zgemmah9combo

[current.php] - add _usb.zip

---

sx988/images

Update SW Image V10578 OCTAGON SX988 4K Define OS

Update SW Image V10578 OCTAGON SX988 4K Define OS

---

sf8008m/images

Update OCTAGON Define OS Linux SW V10578

Update OCTAGON Define OS Linux SW V10578

---

sf8008m/images

SW Image Update V10580 OCTAGON Define OS SF8008M

SW Image Update V10580 OCTAGON Define OS SF8008M

---

sx988/images

Update SW Image V10580 OCTAGON Define OS SX988 4K

Update SW Image V10580 OCTAGON Define OS SX988 4K

---

sf8008/images

SW Update Image V10580 OCTAGON Define OS SF8008

SW Update Image V10580 OCTAGON Define OS SF8008

---

sx988/images

Octagon Define US Update SW V10585 SX988 4K

Octagon Define US Update SW V10585 SX988 4K

---

sx988/images

Update SX988 4K Define OS SW V10589 DUAL OS

Update SX988 4K Define OS SW V10589 DUAL OS

---

sf8008m/images

Update SF8008M Define OS SW V10589 DUAL OS

Update SF8008M Define OS SW V10589 DUAL OS

---

sf8008/images

Update SF8008 Define OS SW V10589 DUAL OS

Update SF8008 Define OS SW V10589 DUAL OS

---

sfx6008/images

Update SFX6008 SFX6018 Define OS SW V10572 DUAL OS

Update SFX6008 SFX6018 Define OS SW V10572 DUAL OS

---

sfx6008/images

SW Update V10575 OCTAGON SFX6008 SFX6018 DUAL OS

SW Update V10575 OCTAGON SFX6008 SFX6018 DUAL OS

---

ustym4kpro/images

Hi I'm new I would like to be able to insert the areadeltasat image in the system for online upload.
Thank you ..

Add Images areadeltasat 10.3 r18 ustym4kpro 

---

sfx6008/images

OCTAGON SFX6008 SFX6018 Update SW V10576 Define OS

OCTAGON SFX6008 SFX6018 Update SW V10576 Define OS

---

sx988/images

OCTAGON SX988 4K Define OS SW Update V10590

OCTAGON SX988 4K Define OS SW Update V10590

---

sf8008m/images

Octagon SF8008M Define OS SW Update V10590

Octagon SF8008M Define OS SW Update V10590

---

sf8008/images

Octagon SF8008 Define OS SW Update V10590

Octagon SF8008 Define OS SW Update V10590

---

sx988/images

OCTAGON SX988 4K Define OS SW Update V10593

OCTAGON SX988 4K Define OS SW Update V10593

---

sfx6008/images

OCTAGON SFX6008 SFX6018 Update SW V10578 Define OS

OCTAGON SFX6008 SFX6018 Update SW V10578 Define OS

---

sf8008/images

OCTAGON SF8008 Define OSSW Update V10597

OCTAGON SF8008 Define OSSW Update V10597

---

sf8008m/images

OCTAGON SF8008M Define OS SW Update V10597

OCTAGON SF8008M Define OS SW Update V10597

---

sx988/images

OCTAGON SX988 4K Define OS SW Update V10597

OCTAGON SX988 4K Define OS SW Update V10597

---

sfx6008/images

OCTAGON SFX6008 SFX6018 Define OS SW Update V10580

OCTAGON SFX6008 SFX6018 Define OS SW Update V10580

---

sx988/images

OCTAGON SX988 4K Update Define OS SW V10598

OCTAGON SX988 4K Update Define OS SW V10598

---

sf8008m/images

OCTAGON SF8008M Update Define OS SW V10598

OCTAGON SF8008M Update Define OS SW V10598

---

sf8008/images

OCTAGON SF8008 Update Define OS SW V10598

OCTAGON SF8008 Update Define OS SW V10598

---

sfx6008/images

Octagon SFX6008 SFX6018 enigma2 Factory Image

Octagon SFX6008 SFX6018 enigma2 Factory Image

---

sf8008/images

SF8008 FACTORY DEFAULT IMAGE 24 11 2022

SF8008 FACTORY DEFAULT IMAGE 24 11 2022

---

sf8008m/images

SF8008M FACTORY DEFAULT IMAGE 24 11 2022

SF8008M FACTORY DEFAULT IMAGE 24 11 2022

---

sf8008/images

please use this one , Define os Factory Image !

please use this one , Define os Factory Image !

---

sx88v2/images

First Release OCTAGON SX88V2 - SX888V2 Define OS

First Release OCTAGON SX88V2 - SX888V2 Define OS

---

sfx6008/images

OCTAGON SFX6008 SFX6018 SW Update V10582 Define OS

OCTAGON SFX6008 SFX6018 SW Update V10582 Define OS

---

sf8008/images

OCTAGON SF8008 V10605 Define OS Update!

OCTAGON SF8008 V10605 Define OS Update!

---

sf8008m/images

OCTAGON SF8008M V10605 Define OS Update!

OCTAGON SF8008M V10605 Define OS Update!

---

sx988/images

OCTAGON SX988 4K Define OS Update SW V10605!

OCTAGON SX988 4K Define OS Update SW V10605!

---

sx88v2/images

OCTAGON SX88 V2 4K - SX888 V2 4K Define OS Update

OCTAGON SX88 V2 4K - SX888 V2 4K Define OS Update

---

ip8/images

Anadol IP8 4K First Releaese Define OS 06 01 23

Anadol IP8 4K First Releaese Define OS 06 01 23

---

sx88v2/images

SX88 V2 4K - SX888 V2 4K Update Define OS V10606

SX88 V2 4K - SX888 V2 4K Update Define OS V10606

---

sfx6008/images

SFX6008 & SFX6018 Update Define OS SW V10583

SFX6008 & SFX6018 Update Define OS SW V10583

---

sf8008/images

SF8008 Update Define OS SW V10607

SF8008 Update Define OS SW V10607

---

sf8008m/images

SF8008M Update Define OS SW V10607

SF8008M Update Define OS SW V10607

---

sx88v2/images

Update SX88V2 4K SX888V2 4K Define OS V10607

Update SX88V2 4K SX888V2 4K Define OS V10607

---

sx988/images

Update SX988 4K Define OS SW V10607

Update SX988 4K Define OS SW V10607

---

ip8/images

ANADOL IP8 4K DUAL OS SW Update

ANADOL IP8 4K DUAL OS SW Update

---

ip8/images

Update Define OS SW V10612 Anadol IP8 4K

Update Define OS SW V10612 Anadol IP8 4K

---

sx88v2/images

Update Define OS SW V10612 SX88V2 4K & SX888V2 4K

Update Define OS SW V10612 SX88V2 4K & SX888V2 4K

---

sf8008m/images

Define OS SW Update V10622 OCTAGON SF8008M 4K

Define OS SW Update V10622 OCTAGON SF8008M 4K

---

sf8008/images

Define OS SW Update V10622 OCTAGON SF8008 4K

Define OS SW Update V10622 OCTAGON SF8008 4K

---

sx988/images

Define OS SW Update V10622 OCTAGON SX988 4K

Define OS SW Update V10622 OCTAGON SX988 4K

---

sx88v2/images

Define OS SW Update V10622 SX88 V2 4K-SX888 V2 4K

Define OS SW Update V10622 SX88 V2 4K-SX888 V2 4K

---

ip8/images

Define OS SW V10622 Update ANADOL IP8 4K

Define OS SW V10622 Update ANADOL IP8 4K

---

sfx6008/images

Define OS SW Updte V10589 OCTAGON SFX6008 SFX6018

Define OS SW Updte V10589 OCTAGON SFX6008 SFX6018

---

sf8008/images

Octagon SF8008 Define os SW Update V10627

Octagon SF8008 Define os SW Update V10627

---

sf8008m/images

OCTAGON SF8008M Define OS SW Update V10627

OCTAGON SF8008M Define OS SW Update V10627

---

sx88v2/images

OCTAGON SX88V2 SX888V2 4K Define OS SW Update V10627

OCTAGON SX88V2 SX888V2 4K Define OS SW Update V10627

---

sfx6008/images

OCTAGON SFX6008 SFX6018 Define OS SW Update V10593

OCTAGON SFX6008 SFX6018 Define OS SW Update V10593

---

ip8/images

ANADOL IP8 4K Define OS SW Update V10627

ANADOL IP8 4K Define OS SW Update V10627

---

sfx6008/images

Update SW V10601 SFX6008 SFX6018 Define os OCTAGON

Update SW V10601 SFX6008 SFX6018 Define os OCTAGON

---

sx88v2/images

Update images SX88V2 SX888V2 4K Octagon Define OS!

Update images SX88V2 SX888V2 4K Octagon Define OS!

---

ip8/images

Update images Anadol IP8 4K

---

sx988/images

Update images SX988 4K OCTAGON V10637

Update images SX988 4K OCTAGON V10637

---

sx988/images

Update images OCTAGON SX988 4K Define OS!

Update images OCTAGON SX988 4K Define OS!

---

sf8008m/images

Update images OCTAGON SF8008M Define os!

Update images OCTAGON SF8008M Define os!

---

sf8008/images

Update images OCTAGON SF8008 Define os!

Update images OCTAGON SF8008 Define os!

---

sf8008/images

Update images Define OS OCTAGON V10644 SF8008 ALL

Update images Define OS OCTAGON V10644 SF8008 ALL

---

sf8008m/images

Update images SF8008 MINI V10645

Update images SF8008 MINI V10645

---

sf8008/images

Update images SF8008 V10645

---

sf8008/images

Factory Image Update E2 OpenATV + Define 16-01-24

Factory Image Update E2 OpenATV + Define 16-01-24

---

sf8008/images

Octagon enigma2 7.3 Factory Image FTP Access fix

Octagon enigma2 7.3 Factory Image FTP Access fix

---

sf8008/images

Clean Up old Image Files

---

h11/images
h8/images
h9combo/images
h9se/images
multiboxpro/images
novaler4k/images
novaler4kpro/images
novaler4kse/images
zgemmah11s/images
zgemmah82h/images
zgemmah92hse/images
zgemmah9combo/images
zgemmah9se/images
zgemmah9sse/images
zgemmah9twin/images

[EGAMI] - add 10.5

---

sf8008/images

Factory E2 OpenATV 7.3 Update Cardslot fix.

Factory E2 OpenATV 7.3 Update Cardslot fix.

---

sfx6008/images

Update images SFX6008-SFX6018 SW V10604 OCTAGON 28-03-24

Update images SFX6008-SFX6018 SW V10604 OCTAGON 28-03-24

---

ip8/images

Update images Anadol IP8 4K SW V10647

Update images Anadol IP8 4K SW V10647

---

sx88v2/images

Update images OCTAGON SX88 V2 4K - SX888 V2 4K SW V10647 Define OS 29,03,24

Update images OCTAGON SX88 V2 4K - SX888 V2 4K SW V10647

---

sx988/images

Update images OCTAGON SX988 4K SW V10647 Define OS 29,03,24

Update images OCTAGON SX988 4K SW V10647 Define OS 29,03,24

---

sx988/images

SW Versions Number corrected.

---

sf8008m/images

Update images SF8008M V10651 Define os SW

Update images SF8008M V10651 Define os SW

---

sx988/images

Update images SX988 4K Define OS SW V10651

Update images SX988 4K Define OS SW V10651

---

sx88v2/images

Update images V10657
